version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mebank
    ports:
      - "5435:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
